nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []
imagePullPolicy: IfNotPresent

global:
  image:
    registry: chaitin
    tag: ""
    region: ""
  # Global enable port mode to expose services, affecting the modification of service exposure mode for: detector and chaos, 
  # enabling this option will add multiple configmap loads and modify configuration files, and will modify nginx.conf file.
  # It is recommended to keep this option enabled
  exposeServicesAsPorts:
    enabled: true
  # Set SafeLine WAF console to be accessed through domain name, e.g.: demo.waf-ce.chaitin.cn
  ingress:
    # Whether to enable SafeLine WAF control through domain access, not enabled by default
    enabled: false
    hostname: waf.local
    ingressClassName: nginx
    annotations:
      # The storage value of proxy-body-size in the annotation, the maximum value of file upload size, 
      # i.e., the value of nginx.ingress.kubernetes.io/proxy-body-size, default is 200M
      proxyBodySize: 200M
    pathType: ImplementationSpecific
    path: /
    tls:
      # Whether to load the HTTPS domain certificate Secret outside HelmChart, if yes, please fill in the Secret name. 
      # By default, it is not filled in and the domain name only enables http access.
      # If you fill in the following items, please create the corresponding Secret before running the HelmChart.
      secretName: ""

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    database:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
      annotations: {}

    detectorLogs:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

    tengineLogs:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

    nginx:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

    mgt:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

    detector:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

    tengine:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

    luigi:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}
    
    chaos:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteMany
      size: 1Gi
      annotations: {}

database:
  type: internal
  internal:
    serviceAccountName: ""
    automountServiceAccountToken: false
    image:
      registry: ''
      repository: safeline-postgres
      tag: 15.2
    password: changeit
    shmSizeLimit: 512Mi
    resources:
    #  requests:
    #    memory: 256Mi
    #    cpu: 100m
    livenessProbe:
      timeoutSeconds: 1
    readinessProbe:
      timeoutSeconds: 1
    nodeSelector: {}
    tolerations: []
    affinity: {}
    priorityClassName:
    initContainer:
      migrator: {}
      # resources:
      #  requests:
      #    memory: 128Mi
      #    cpu: 100m
      permissions: {}
      # resources:
      #  requests:
      #    memory: 128Mi
      #    cpu: 100m
  external:
    host: ""
    port: ""
    username: ""
    password: ""
    coreDatabase: "safeline-ce"
    dbname: "safeline-ce"
    existingSecret: ""
    sslmode: "disable"
  maxIdleConns: 100
  maxOpenConns: 900
  podAnnotations: {}

mgt:
  image:
    registry: ''
    repository: safeline-mgt
    tag: ""
  service:
    type: NodePort
    web:
      nodePort: 31443
  resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 1000Mi
  #   requests:
  #     cpu: 100m
  #     memory: 100Mi
  podAnnotations: {}
  serviceAccountName: ""
  automountServiceAccountToken: false
  replicas: 1
  revisionHistoryLimit: 10
  startupProbe:
    enabled: false
    initialDelaySeconds: 10
  nodeSelector: {}
  affinity: {}
  tolerations: []
  priorityClassName: 

fvm:
  image:
    registry: ''
    repository: safeline-fvm
    tag: ""
  service:
    type: ClusterIP
  resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 1000Mi
  #   requests:
  #     cpu: 100m
  #     memory: 100Mi
  podAnnotations: {}
  serviceAccountName: ""
  automountServiceAccountToken: false
  replicas: 1
  revisionHistoryLimit: 10
  startupProbe:
    enabled: false
    initialDelaySeconds: 10
  nodeSelector: {}
  affinity: {}
  tolerations: []
  priorityClassName: 


detector:
  image:
    registry: ''
    repository: safeline-detector
    tag: ""
  resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 1000Mi
  #   requests:
  #     cpu: 100m
  #     memory: 100Mi
  podAnnotations: {}
  serviceAccountName: ""
  automountServiceAccountToken: false
  replicas: 1
  revisionHistoryLimit: 10
  startupProbe:
    enabled: false
    initialDelaySeconds: 10
  nodeSelector: {}
  affinity: {}
  tolerations: []
  priorityClassName: 

tengine:
  image:
    registry: ''
    repository: safeline-tengine
    tag: ""
  resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 1000Mi
  #   requests:
  #     cpu: 100m
  #     memory: 100Mi
  podAnnotations: {}
  serviceAccountName: ""
  automountServiceAccountToken: false
  replicas: 1
  revisionHistoryLimit: 10
  startupProbe:
    enabled: false
    initialDelaySeconds: 10
  nodeSelector: {}
  affinity: {}
  tolerations: []
  priorityClassName: 

luigi:
  image:
    registry: ''
    repository: safeline-luigi
    tag: ""
  service:
    type: ClusterIP
  resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 1000Mi
  #   requests:
  #     cpu: 100m
  #     memory: 100Mi
  podAnnotations: {}
  serviceAccountName: ""
  automountServiceAccountToken: false
  replicas: 1
  revisionHistoryLimit: 10
  startupProbe:
    enabled: false
    initialDelaySeconds: 10
  nodeSelector: {}
  affinity: {}
  tolerations: []
  priorityClassName: 

chaos:
  image:
    registry: ''
    repository: safeline-chaos
    tag: ""
  service:
    type: ClusterIP
  resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 1000Mi
  #   requests:
  #     cpu: 100m
  #     memory: 100Mi
  podAnnotations: {}
  serviceAccountName: ""
  automountServiceAccountToken: false
  replicas: 1
  revisionHistoryLimit: 10
  startupProbe:
    enabled: false
    initialDelaySeconds: 10
  nodeSelector: {}
  affinity: {}
  tolerations: []
  priorityClassName: 
